import type { Metadata } from "next";
import Header from "./components/CustomAppBar";
import React from "react";
import { CustomTheme } from "./components/CustomTheme";

export const metadata: Metadata = {
  title: "MUI Next.js TestApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <CustomTheme>
        <body>
          <Header />

          {children}
        </body>
      </CustomTheme>
    </html>
  );
}
