import type { Metadata } from "next";
import Header from "./components/CustomAppBar";
import CssBaseline from "@mui/material/CssBaseline";
import React from "react";

export const metadata: Metadata = {
  title: "MUI Next.js TestApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <CssBaseline />
      <body>
        <Header />

        {children}
      </body>
    </html>
  );
}
